# Generated by Django 3.2.6 on 2021-09-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attende',
            name='room_name',
            field=models.CharField(default='C424', max_length=4),
        ),
    ]
