# Generated by Django 3.2.6 on 2021-09-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0002_alter_attende_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attende',
            name='intime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attende',
            name='outtime',
            field=models.TimeField(),
        ),
    ]
