# Generated by Django 3.2.6 on 2021-09-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0007_auto_20210910_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attende',
            name='intime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attende',
            name='outtime',
            field=models.TextField(blank=True, max_length=8),
        ),
    ]
