# Generated by Django 3.2.6 on 2021-09-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0008_auto_20210910_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attende',
            name='intime',
            field=models.TimeField(blank=True),
        ),
    ]
