# Generated by Django 3.2.6 on 2021-09-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0011_alter_attende_intime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attende',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attende',
            name='intime',
        ),
        migrations.RemoveField(
            model_name='attende',
            name='outtime',
        ),
        migrations.AddField(
            model_name='attende',
            name='date_in_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attende',
            name='date_out_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
