# Generated by Django 3.2.6 on 2021-09-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0012_auto_20210911_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attende',
            name='date_out_time',
            field=models.DateTimeField(),
        ),
    ]
