# Generated by Django 3.2.8 on 2021-10-27 21:21

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0015_alter_attende_date_out_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attende',
            name='date_in_time',
        ),
        migrations.RemoveField(
            model_name='attende',
            name='date_out_time',
        ),
        migrations.RemoveField(
            model_name='attende',
            name='room_name',
        ),
        migrations.AddField(
            model_name='attende',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attende',
            name='in_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attende',
            name='out_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attende',
            name='uid',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000)]),
        ),
    ]
